services:
  db:
    image: postgres:14
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  tester:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/testing
    working_dir: /testing
    command: tail -f /dev/null
    environment:
      - DOCKER_CONTAINER=1
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
