name: Dependency Check

on:
  pull_request:
    paths:
      - 'pyproject.toml'
      - 'requirements*.txt'
      - 'tox.ini'
  schedule:
    # Run weekly on Mondays
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v4

    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: moderate

  pip-audit:
    name: Pip Audit
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install pip-audit
      run: |
        python -m pip install --upgrade pip
        pip install pip-audit

    - name: Run pip-audit
      run: |
        # Install the package to get all dependencies
        pip install -e ".[dev]"

        # Run pip-audit and save results
        pip-audit --format json --output pip-audit-report.json || true

        # Display results
        pip-audit || true

    - name: Upload pip-audit report
      uses: actions/upload-artifact@v4
      with:
        name: pip-audit-report
        path: pip-audit-report.json
        retention-days: 30

  outdated-check:
    name: Check Outdated Dependencies
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Check for outdated packages
      run: |
        python -m pip install --upgrade pip
        pip install pip-outdated

        # Install current dependencies
        pip install -e ".[dev]"

        # Check for outdated packages
        echo "## Outdated Dependencies" > outdated-report.md
        echo "" >> outdated-report.md
        pip list --outdated --format=markdown >> outdated-report.md || echo "No outdated packages found." >> outdated-report.md

        # Display report
        cat outdated-report.md

    - name: Upload outdated report
      uses: actions/upload-artifact@v4
      with:
        name: outdated-dependencies
        path: outdated-report.md
        retention-days: 30

  license-check:
    name: License Compatibility Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Check licenses
      run: |
        python -m pip install --upgrade pip
        pip install pip-licenses

        # Install the package
        pip install -e ".[dev]"

        # Generate license report
        echo "## License Report" > license-report.md
        echo "" >> license-report.md
        pip-licenses --format=markdown --with-urls --with-description >> license-report.md

        # Check for problematic licenses
        pip-licenses --fail-on="GPL;LGPL;AGPL;SSPL" || echo "Warning: Found copyleft licenses"

    - name: Upload license report
      uses: actions/upload-artifact@v4
      with:
        name: license-report
        path: license-report.md
        retention-days: 30
